/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('Answers', [{
      questionId: 1,
      answer: 'Четвертое',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 1,
      answer: 'Второе',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 1,
      answer: 'Третье',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 1,
      answer: 'Первое',
      status: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 2,
      answer: 'Четвертое',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 2,
      answer: 'Пятое',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 2,
      answer: 'Третье',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 2,
      answer: 'Второе',
      status: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 3,
      answer: 'Цветок',
      status: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 3,
      answer: 'Зонт',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 3,
      answer: 'Табурет',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 3,
      answer: 'Бабёр',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 4,
      answer: 'Серый',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 4,
      answer: 'Пурпурный',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 4,
      answer: 'Белый',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 4,
      answer: 'Синий',
      status: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 5,
      answer: 'Ножка',
      status: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 5,
      answer: 'Спинка',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 5,
      answer: 'Дно',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 5,
      answer: 'Лампочка',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 6,
      answer: 'Борщь',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 6,
      answer: 'Стена',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 6,
      answer: 'Гриб',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 6,
      answer: 'Стол',
      status: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 7,
      answer: 'Стул',
      status: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 7,
      answer: 'Пень',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 7,
      answer: 'Крыса',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 7,
      answer: 'Молот Тора',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 8,
      answer: 'Моются',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 8,
      answer: 'Танцуют',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 8,
      answer: 'Режут бутики',
      status: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      questionId: 8,
      answer: 'Сидят',
      status: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ]);
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Answers');
  },
};
